# Project information
site_name: Works by Mikel Imaz
site_url: https://mikel-imaz.github.io/mikel-imaz
site_author: Mikel Imaz
site_description: My works

# Copyright
copyright: Copyright &copy; 2025 Mikel Imaz

# Configuration
theme:
  name: material
  icon:
    logo: material/face-man-profile
  features:
    - navigation.instant

# Extensions
markdown_extensions: 
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Welcome: index.md
  - Data Science: ds.md
  - AI apps: ai.md
  - Lectures: lectures.md
  - Python: python.md
  - GitHub profile: https://github.com/mikel-imaz

# Extras
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js